apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      name: schema-registry-pod
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:latest # Consider specifying a specific version
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry-service"
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: "zookeeper-service:2181"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://schema-registry-service:8081"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: SCHEMA_REGISTRY_DEBUG
              value: "true"
