kubectl apply -f volumes/mongo-pvc.yml
kubectl apply -f services/mockrater-loadbalancer.yml
kubectl apply -f services/mockrater-service.yml
kubectl apply -f deployments/mockrater-deployment.yml
kubectl apply -f services/mongo-service.yml
kubectl apply -f deployments/mongo-deployment.yml
kubectl apply -f services/mongo-express-loadbalancer.yml
kubectl apply -f deployments/mongo-express-deployment.yml
kubectl apply -f services/redis-svc.yml
kubectl apply -f deployments/redis-dp.yml
kubectl apply -f deployments/esrating-worker-dp.yml
kubectl apply -f deployments/quoteprocess-deployment.yml
kubectl apply -f deployments/quotedetails-deployment.yml
kubectl apply -f services/quotemanager-loadbalancer.yml
kubectl apply -f deployments/quotemanager-deployment.yml
