kubectl apply -f volumes/mongo-pvc.yml
kubectl apply -f deployments/mongo-dp.yml
kubectl apply -f services/mongo-svc.yml
kubectl apply -f deployments/redis-dp.yml
kubectl apply -f services/redis-svc.yml
kubectl apply -f deployments/esrater-dp.yml
kubectl apply -f services/esrater-svc.yml
kubectl apply -f deployments/quotedetails-dp.yml
kubectl apply -f deployments/quoteprocess-dp.yml
kubectl apply -f deployments/quotemanager-dp.yml
kubectl apply -f services/quotemanager-ingress.yml