kubectl delete deployments mongo-dp
kubectl delete services mongo-svc
kubectl delete deployments redis-dp
kubectl delete services redis-svc
kubectl delete deployments esrater-dp
kubectl delete services esrater-svc
kubectl delete deployments quotedetails-dp
kubectl delete deployments quoteprocess-dp
kubectl delete deployments quotemanager-dp
kubectl delete pvc mongo-pvc