apiVersion: v1
kind: Service
metadata:
  name: mongo-express-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 9881
      targetPort: 8081