apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 31092