kubectl apply -f volumes/kafka-pvc.yml
kubectl apply -f volumes/mongo-pvc.yml
kubectl apply -f services/mockrater-loadbalancer.yml
kubectl apply -f services/mockrater-service.yml
kubectl apply -f deployments/mockrater-deployment.yml
kubectl apply -f services/mongo-service.yml
kubectl apply -f deployments/mongo-deployment.yml
kubectl apply -f deployments/mongo-express-deployment.yml
kubectl apply -f services/zookeeper-service.yml
kubectl apply -f deployments/zookeeper-deployment.yml
kubectl apply -f services/kafka-service.yml
kubectl apply -f deployments/kafka-deployment.yml
kubectl apply -f services/schema-registry-service.yml
kubectl apply -f deployments/schema-registry-deployment.yml
kubectl apply -f deployments/quoterater-deployment.yml
kubectl apply -f deployments/quoteprocess-deployment.yml
kubectl apply -f deployments/quotedetails-deployment.yml
kubectl apply -f services/quotemanager-loadbalancer.yml
kubectl apply -f deployments/quotemanager-deployment.yml
