apiVersion: apps/v1
kind: Deployment
metadata:
  name: esrater-dp
  labels:
    app: esrater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esrater
  template:
    metadata:
      name: esrater-pod
      labels:
        app: esrater
    spec:
      containers:
        - name: esrater
          image: covcloud/esrater:0.0.7-SNAPSHOT
          ports:
            - containerPort: 8080

