apiVersion: apps/v1
kind: Deployment
metadata:
  name: esrater-dp
  labels:
    app: esrater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esrater
  template:
    metadata:
      name: esrater-pod
      labels:
        app: esrater
    spec:
      containers:
        - name: esrater
          image: covcloud/es-reference-rater:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9097
          env:
            - name: ENV
              value: "dev"
            - name: MONGO_URI
              value: "mongodb://mongo-svc:27017/quotedetails"
            - name: REDIS_HOST
              value: "redis-svc"
            - name: REDIS_PORT
              value: "6379"
