apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotedetails-dp
  labels:
    app: quotedetails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotedetails
  template:
    metadata:
      name: quotedetails-pod
      labels:
        app: quotedetails
    spec:
      containers:
        - name: quotedetails
          image: covcloud/quote-details:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9098
          env:
            - name: ENV
              value: "dev"
            - name: MONGO_URI
              value: "mongodb://mongo-svc:27017/quotedetails"
            - name: REDIS_HOST
              value: "redis-svc"
            - name: REDIS_PORT
              value: "6379"

