apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotemanager-dp
  labels:
    app: quotemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotemanager
  template:
    metadata:
      name: quotemanager-pod
      labels:
        app: quotemanager
    spec:
      containers:
        - name: quotemanager
          image: covcloud/quote-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: ENV
              value: "dev"
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/quoteprocess"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: RATING_SERVICE
              value: "http://esrater-svc:8080/api/v1/es/"
            - name: RATING_SCENARIO
              value: "standard"
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 20

