apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoteprocess-dp
  labels:
    app: quoteprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoteprocess
  template:
    metadata:
      name: quoteprocess-pod
      labels:
        app: quoteprocess
    spec:
      containers:
        - name: quoteprocess
          image: covcloud/quote-process:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
          env:
            - name: ENV
              value: "dev"
            - name: MONGO_URI
              value: "mongodb://mongo-svc:27017/quoteprocess"
            - name: REDIS_HOST
              value: "redis-svc"
            - name: REDIS_PORT
              value: "6379"


