apiVersion: v1
kind: Pod
metadata:
  name: mongo-express-pod
  labels:
    app: mongo-express
spec:
  containers:
    - name: mongo-express
      image: mongo-express
      ports:
        - containerPort: 8081
      env:
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://mongo:27017/"
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-service # Assuming the MongoDB service is named 'mongo-service'
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"